/*
Colas PICARD
11410822

TP2 - Conception de BDR - Fragmentation
*/

/*
Exercice 1
*/
--Question 1
--sur orapeda1
CREATE DATABASE LINK lien1to2 CONNECT TO M1IF35 IDENTIFIED BY MIF35 USING 'orapeda2';
CREATE DATABASE LINK lien1to3 CONNECT TO M1IF35 IDENTIFIED BY MIF35 USING 'orapeda3';

--sur orapeda2
CREATE DATABASE LINK lien2to1 CONNECT TO M1IF35 IDENTIFIED BY MIF35 USING 'orapeda1';
CREATE DATABASE LINK lien2to3 CONNECT TO M1IF35 IDENTIFIED BY MIF35 USING 'orapeda3';

--sur orapeda3
CREATE DATABASE LINK lien3to1 CONNECT TO M1IF35 IDENTIFIED BY MIF35 USING 'orapeda1';
CREATE DATABASE LINK lien3to2 CONNECT TO M1IF35 IDENTIFIED BY MIF35 USING 'orapeda2';

--Question 2
--sur orapeda1(Lyon)
CREATE TABLE Usine1 AS 
  (SELECT * FROM BDENS.USINE WHERE dept = 01 OR dept = 42 OR dept = 69);

CREATE TABLE ChaineProd1 AS 
  (SELECT * FROM BDENS.CHAINEPROD WHERE IDU IN (SELECT IDU FROM USINE1));
  
CREATE TABLE Boutique1 AS 
  (SELECT IDB, NOM, VILLE, MAIL, TYPEB  FROM BDENS.BOUTIQUE WHERE TYPEB LIKE 'franchise');
CREATE TABLE BoutiqueCA1 AS 
  (SELECT IDB, CAMOYEN FROM BDENS.BOUTIQUE);

CREATE TABLE confiserie1 AS 
  (SELECT * FROM BDENS.CONFISERIE);

CREATE TABLE vente1 AS 
  (SELECT * FROM BDENS.vente WHERE IDU IN (SELECT IDU FROM USINE1));

CREATE TABLE detail1 AS 
  (SELECT * FROM BDENS.DETAIL WHERE IDU IN (SELECT IDU FROM USINE1));

--sur orapeda2
CREATE TABLE Usine2 AS 
  SELECT * FROM BDENS.USINE@lien2to1 WHERE dept = 07 OR dept = 26 OR dept = 38;

CREATE TABLE ChaineProd2 AS 
  (SELECT * FROM BDENS.CHAINEPROD@lien2to1 WHERE IDU IN (SELECT IDU FROM USINE2));

CREATE TABLE Boutique2 AS 
  (SELECT IDB, NOM, VILLE, MAIL, TYPEB  FROM BDENS.BOUTIQUE@lien2to1 WHERE TYPEB LIKE 'usine');
CREATE TABLE BoutiqueCA2 AS 
  (SELECT IDB, CAMOYEN FROM BDENS.BOUTIQUE@lien2to1 WHERE 1=2);

CREATE TABLE confiserie2 AS 
  (SELECT * FROM BDENS.CONFISERIE@lien2to1);

CREATE TABLE vente2 AS 
  (SELECT * FROM BDENS.vente@lien2to1 WHERE IDU IN (SELECT IDU FROM USINE2));

CREATE TABLE detail2 AS 
  (SELECT * FROM BDENS.DETAIL@lien2to1 WHERE IDU IN (SELECT IDU FROM USINE2));

--sur orapeda3
CREATE TABLE Usine3 AS 
  SELECT * FROM BDENS.USINE@lien3to1 WHERE dept = 73 OR dept = 74;

CREATE TABLE ChaineProd3 AS 
  (SELECT * FROM BDENS.CHAINEPROD@lien3to1 WHERE IDU IN (SELECT IDU FROM USINE3));
 
CREATE TABLE Boutique3 AS 
  (SELECT IDB, NOM, VILLE, MAIL, TYPEB  FROM BDENS.BOUTIQUE@lien3to1 WHERE TYPEB LIKE 'autre');
CREATE TABLE BoutiqueCA3 AS 
  (SELECT IDB, CAMOYEN FROM BDENS.BOUTIQUE@lien3to1 WHERE 1=2);

CREATE TABLE confiserie3 AS 
  (SELECT * FROM BDENS.CONFISERIE@lien3to1);

CREATE TABLE vente3 AS 
  (SELECT * FROM BDENS.vente@lien3to1 WHERE IDU IN (SELECT IDU FROM USINE3));

CREATE TABLE detail3 AS 
  (SELECT * FROM BDENS.DETAIL@lien3to1 WHERE IDU IN (SELECT IDU FROM USINE3));
  
--Question 3
SELECT v.DATEV, v.MONTANT FROM USINE1 u INNER JOIN DETAIL1 d ON u.IDU = d.IDU INNER JOIN VENTE1 v ON v.IDU = d.IDU NATURAL JOIN CONFISERIE1 c WHERE to_char('YY', v.DATEV) = 14 AND c.TYPEC LIKE 'guimauve' AND u.DEPT=69;

--Question 4
CREATE VIEW UsineG AS SELECT * FROM USINE1@lien2to1 

--Question 5
